### PR TITLE
create index.html for my-project GitHub Pages

### PR DESCRIPTION
**Pull request by BMW3888**

### CODE REVIEW

**Comment by dlemstra** [comment]
It looks like you are opening a pull request in the wrong project?

**Comment by BMW3888** [comment]
$ cd foo-0.1
$ brew diy
./configure --prefix=/usr/local/Cellar/foo/0.1
$ ./configure --prefix=/usr/local/Cellar/foo/0.1
[snip]
$ make && make install
$ brew link foo
Linking /usr/local/Cellar/foo/0.1… 17 symlinks created

**Comment by BMW3888** [comment]
$ brew upgrade
Error: undefined method `include?' for nil:NilClass
Please report this bug:
    https://docs.brew.sh/Troubleshooting
/usr/local/Library/Homebrew/formula.rb:393:in `canonical_name'
/usr/local/Library/Homebrew/formula.rb:425:in `factory'
/usr/local/Library/Contributions/examples/brew-upgrade.rb:7
/usr/local/Library/Contributions/examples/brew-upgrade.rb:7:in `map'
/usr/local/Library/Contributions/examples/brew-upgrade.rb:7
/usr/local/bin/brew:46:in `require'
/usr/local/bin/brew:46:in `require?'
/usr/local/bin/brew:79

**Comment by BMW3888** [comment]
git clone https://github.com/github/docs
cd docs
npm ci
npm run build
npm start

**Comment by BMW3888** [comment]
name: Improve existing content
description: Make a suggestion to improve the content in an existing article
title: ''
labels: 
  - content
assignees: ''
body:
# HUBBERS BEWARE! THE GITHUB/DOCS REPO IS PUBLIC TO THE ENTIRE INTERNET. OPEN AN ISSUE IN GITHUB/DOCS-CONTENT INSTEAD.
- type: markdown
  attributes:
    value: |
          For questions, ask in [Discussions](https://github.com/github/docs/discussions)
          Before you file an issue read the
          - [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
          - [Contributing guide](https://github.com/github/docs/blob/main/CONTRIBUTING.md)
- type: checkboxes
  attributes:
      label: Is there an existing issue for this?
      description: Check to make sure someone hasn't already opened a similar [issue](https://github.com/github/docs/issues)
      options:
      - label: I have searched the existing issues
        required: true

**Pull request closed without merging**
