### PR TITLE
Add other methods for rich menu.

### PR DESCRIPTION
**Pull request by Ben67366**
@dlemstra 
Hi, I'm trying to add other methods for rich menu.
And don't know how to deSerialize object (with Interfaces) from JSON.
Can you help me with that?

```
Test method Line.Tests.LineBotTests+TheGetRichMenuMethod.ShouldGetRichMenu threw exception: 
Newtonsoft.Json.JsonSerializationException: Could not create an instance of type Line.IRichMenuSize. Type is an interface or abstract class and cannot be instantiated. Path 'size.width', line 1, position 92.
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
```

### CODE REVIEW

**Comment by Ben67366** [comment]
Sorry maybe it's too early and lack of researches to ask you at this moments.
I will do more research on this later.

**Comment by dlemstra** [comment]
Could you please create PR's for each separate method? Or are you already planning this and that is why you closed the issue?

**Comment by Ben67366** [comment]
@dlemstra Yeah. let me do it little by little.
Some methods that I don't know how to implement it.
If you have time, can you check them and give me some hints?

Method for Rich Menu:
 - Get rich menu (How to convert the JSON response to rich menu object.)
 - (Done) Create rich menu
 - Delete rich menu
 - Get rich menu ID of user
 - Link rich menu to user
 - Unlink rich menu from user
 - Download rich menu image
 - Upload rich menu image (Need consider how to pass the image file to HTTPPost)
 - Get rich menu list

**Comment by dlemstra** [comment]
I will try to create separate issue for all the operations and add an implementation proposal there. Probably this weekend.

**Pull request closed without merging**
